model:
  arch: blip2_baichuan13b_instruct
  load_finetuned: False
  load_pretrained: True
  pretrained: ""

  finetuned: ""

  # vit encoder
  image_size: 448
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # LLM
  llm_model: "/home/share/tianxin/output/baichuan-13B-sft/4node_v8_20230430/checkpoint-5600"
  
  # generation configs
  prompt: "###问题：\n{}\n\n###答案："

preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 448
        eval:
          name: "blip_image_eval"
          image_size: 448
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
