model:
  arch: blip2_baichuan7b_instruct
  load_finetuned: False
  load_pretrained: True
  # pretrained: "/home/share/yexiaohan/model/blip2_pretrain_s2_du_260410/checkpoint.pth"
  # pretrained: "/home/yexiaohan/code/LAVIS-CMM-dev/lavis/output/BLIP2/Instruct/20230718151/checkpoint_0.pth"
  pretrained: "/home/yexiaohan/code/LAVIS-CMM-dev/lavis/output/BLIP2/Pretrain_stage2_0628_ep3_TESTDU_IN/20230715194/checkpoint_130205_processed.pth"

  finetuned: ""

  # vit encoder
  image_size: 448
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # LLM
  llm_model: "/home/share/tianxin/output/baichuan-7B-sft/v8_20230430/checkpoint-2200"

  peft_type: "lora"
  
  # generation configs
  prompt: "###问题：\n{}\n\n###答案："

preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 448
        eval:
          name: "blip_image_eval"
          image_size: 448
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
