model:
  arch: blip2_glm_instruct
  load_finetuned: True

  pretrained: ""
  finetuned: "/home/yexiaohan/code/LAVIS-CMM/lavis/output/BLIP2/Pretrain_stage2_Instruct/20230529100/checkpoint_4.pth"

  # vit encoder
  image_size: 504
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # OPT
  llm_model: "/home/yexiaohan/data/llm_model/ChatGLM"

  # generation configs
  prompt: "问：{}\n答："


preprocess:
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 504
        eval:
          name: "blip_image_eval"
          image_size: 504
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
